-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 17:08:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SIAS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SIAS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SIAS` DEFAULT CHARACTER SET utf8 ;
USE `SIAS` ;

-- -----------------------------------------------------
-- Table `SIAS`.`Tb_Pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIAS`.`Tb_Pessoas` (
  `Id_Pessoas` INT NOT NULL AUTO_INCREMENT, -- Adicionado AUTO_INCREMENT
  `Email` VARCHAR(45) NULL,
  `Senha` VARCHAR(255) NULL,
  `Nome` VARCHAR(45) NULL,
  `Sobrenome` VARCHAR(45) NULL,
  `Token` VARCHAR(21) NULL,
  `Img(Perfil)` VARCHAR(45) NULL,
  `Verificado` BLOB NULL,
  PRIMARY KEY (`Id_Pessoas`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SIAS`.`Tb_Candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIAS`.`Tb_Candidato` (
  `CPF` VARCHAR(12) NOT NULL,
  `Tb_Pessoas_Id` INT NOT NULL AUTO_INCREMENT, -- Adicionado AUTO_INCREMENT
  `Area_de_Interesse` VARCHAR(50) NULL,
  `Tipo_de_Contratacao` VARCHAR(45) NULL,
  `Experiencia` VARCHAR(200) NULL,
  `Motivacoes` VARCHAR(200) NULL,
  `Escolaridade` VARCHAR(55) NULL,
  `Genero` VARCHAR(45) NULL,
  `Estado_Civil` VARCHAR(45) NULL,
  `Idade` INT(2) NULL,
  `Autodefinicao` VARCHAR(255) NULL,
  `Cargo_Desejado` VARCHAR(45) NULL,
  `Numero` VARCHAR(12) NULL,
  `Cursos` VARCHAR(45) NULL,
  PRIMARY KEY (`CPF`),
  INDEX `fk_Tb_Candidato_Tb_Pessoas_idx` (`Tb_Pessoas_Id` ASC),
  CONSTRAINT `fk_Tb_Candidato_Tb_Pessoas`
    FOREIGN KEY (`Tb_Pessoas_Id`)
    REFERENCES `SIAS`.`Tb_Pessoas` (`Id_Pessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SIAS`.`Tb_Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIAS`.`Tb_Empresa` (
  `CNPJ` VARCHAR(14) NOT NULL,
  `Tb_Pessoas_Id` INT NOT NULL,
  `Banner` VARCHAR(45) NULL,
  `Area_de_Atuacao` VARCHAR(45) NULL,
  `Facebook` VARCHAR(45) NULL,
  `Github` VARCHAR(45) NULL,
  `Linkedin` VARCHAR(45) NULL,
  `Instagram` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Avaliacao_de_Funcionarios` VARCHAR(45) NULL,
  `Avaliacao_Geral` VARCHAR(45) NULL,
  PRIMARY KEY (`CNPJ`),
  INDEX `fk_Tb_Empresa_Tb_Pessoas1_idx` (`Tb_Pessoas_Id` ASC) ,
  CONSTRAINT `fk_Tb_Empresa_Tb_Pessoas1`
    FOREIGN KEY (`Tb_Pessoas_Id`)
    REFERENCES `SIAS`.`Tb_Pessoas` (`Id_Pessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIAS`.`Tb_Questionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIAS`.`Tb_Questionarios` (
  `Id_Questionario` INT NOT NULL,
  `Area` VARCHAR(255) NULL,
  `Nivel_de_Dificuldade` VARCHAR(55) NULL,
  `Questoes` VARCHAR(255) NULL,
  PRIMARY KEY (`Id_Questionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIAS`.`Tb_Resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIAS`.`Tb_Resultados` (
  `Tb_Questionarios_ID` INT NOT NULL,
  `Tb_Candidato_CPF` VARCHAR(12) NOT NULL,
  `Nota` INT NULL,
  `Quantidade_de_Acertos` INT NULL,
  `Data_do_Questionarios` DATETIME NULL,
  `Numero_de_Tentativas` INT NULL,
  PRIMARY KEY (`Tb_Questionarios_ID`, `Tb_Candidato_CPF`),
  INDEX `fk_Tb_Questionarios_has_Tb_Candidato_Tb_Candidato1_idx` (`Tb_Candidato_CPF` ASC) ,
  INDEX `fk_Tb_Questionarios_has_Tb_Candidato_Tb_Questionarios1_idx` (`Tb_Questionarios_ID` ASC) ,
  CONSTRAINT `fk_Tb_Questionarios_has_Tb_Candidato_Tb_Questionarios1`
    FOREIGN KEY (`Tb_Questionarios_ID`)
    REFERENCES `SIAS`.`Tb_Questionarios` (`Id_Questionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_Questionarios_has_Tb_Candidato_Tb_Candidato1`
    FOREIGN KEY (`Tb_Candidato_CPF`)
    REFERENCES `SIAS`.`Tb_Candidato` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIAS`.`Tb_Anuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIAS`.`Tb_Anuncios` (
  `Id_Anuncios` INT NOT NULL,
  `Categoria` VARCHAR(45) NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Area` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Nivel_Operacional` VARCHAR(45) NULL,
  `Img` VARCHAR(45) NULL,
  `Data_de_Criacao` DATETIME NULL,
  `Modalidade` VARCHAR(45) NULL,
  `Responsabilidade` VARCHAR(45) NULL,
  `Beneficicios` VARCHAR(45) NULL,
  `Requisitos` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Anuncios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIAS`.`Tb_Vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIAS`.`Tb_Vagas` (
  `Tb_Anuncios_Id` INT NOT NULL,
  `Tb_Empresa_CNPJ` VARCHAR(14) NOT NULL,
  `Estados` VARCHAR(45) NULL,
  `Data_de_Termino` DATETIME NULL,
  PRIMARY KEY (`Tb_Anuncios_Id`, `Tb_Empresa_CNPJ`),
  INDEX `fk_Tb_Anuncios_has_Tb_Empresa_Tb_Empresa1_idx` (`Tb_Empresa_CNPJ` ASC) ,
  INDEX `fk_Tb_Anuncios_has_Tb_Empresa_Tb_Anuncios1_idx` (`Tb_Anuncios_Id` ASC) ,
  CONSTRAINT `fk_Tb_Anuncios_has_Tb_Empresa_Tb_Anuncios1`
    FOREIGN KEY (`Tb_Anuncios_Id`)
    REFERENCES `SIAS`.`Tb_Anuncios` (`Id_Anuncios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_Anuncios_has_Tb_Empresa_Tb_Empresa1`
    FOREIGN KEY (`Tb_Empresa_CNPJ`)
    REFERENCES `SIAS`.`Tb_Empresa` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIAS`.`Tb_Inscricoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIAS`.`Tb_Inscricoes` (
  `Tb_Vagas_Tb_Anuncios_Id` INT NOT NULL,
  `Tb_Vagas_Tb_Empresa_CNPJ` VARCHAR(14) NOT NULL,
  `Tb_Candidato_CPF` VARCHAR(12) NOT NULL,
  `Data_de _Inscricao` DATETIME NULL,
  PRIMARY KEY (`Tb_Vagas_Tb_Anuncios_Id`, `Tb_Vagas_Tb_Empresa_CNPJ`, `Tb_Candidato_CPF`),
  INDEX `fk_Tb_Vagas_has_Tb_Candidato_Tb_Candidato1_idx` (`Tb_Candidato_CPF` ASC) ,
  INDEX `fk_Tb_Vagas_has_Tb_Candidato_Tb_Vagas1_idx` (`Tb_Vagas_Tb_Anuncios_Id` ASC, `Tb_Vagas_Tb_Empresa_CNPJ` ASC) ,
  CONSTRAINT `fk_Tb_Vagas_has_Tb_Candidato_Tb_Vagas1`
    FOREIGN KEY (`Tb_Vagas_Tb_Anuncios_Id` , `Tb_Vagas_Tb_Empresa_CNPJ`)
    REFERENCES `SIAS`.`Tb_Vagas` (`Tb_Anuncios_Id` , `Tb_Empresa_CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_Vagas_has_Tb_Candidato_Tb_Candidato1`
    FOREIGN KEY (`Tb_Candidato_CPF`)
    REFERENCES `SIAS`.`Tb_Candidato` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIAS`.`Tb_Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIAS`.`Tb_Cursos` (
  `Id_Cursos` INT NOT NULL,
  `Tema` VARCHAR(45) NULL,
  `Duracao` VARCHAR(45) NULL,
  `Certificado` VARCHAR(45) NULL,
  `Site` VARCHAR(45) NULL,
  `Gratuito` VARCHAR(45) NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`Id_Cursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIAS`.`Tb_Recomendacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIAS`.`Tb_Recomendacoes` (
  `Tb_Candidato_CPF` VARCHAR(12) NOT NULL,
  `Tb_Cursos_Id` INT NOT NULL,
  PRIMARY KEY (`Tb_Candidato_CPF`, `Tb_Cursos_Id`),
  INDEX `fk_Tb_Candidato_has_Tb_Cursos_Tb_Cursos1_idx` (`Tb_Cursos_Id` ASC) ,
  INDEX `fk_Tb_Candidato_has_Tb_Cursos_Tb_Candidato1_idx` (`Tb_Candidato_CPF` ASC) ,
  CONSTRAINT `fk_Tb_Candidato_has_Tb_Cursos_Tb_Candidato1`
    FOREIGN KEY (`Tb_Candidato_CPF`)
    REFERENCES `SIAS`.`Tb_Candidato` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_Candidato_has_Tb_Cursos_Tb_Cursos1`
    FOREIGN KEY (`Tb_Cursos_Id`)
    REFERENCES `SIAS`.`Tb_Cursos` (`Id_Cursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIAS`.`Tb_Respostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIAS`.`Tb_Respostas` (
  `idtb_Respostas` INT NOT NULL,
  `Errada` VARCHAR(255) NULL,
  `Errada2` VARCHAR(255) NULL,
  `Errada3` VARCHAR(255) NULL,
  `Errada4` VARCHAR(255) NULL,
  `Certa` VARCHAR(255) NULL,
  `Tb_Questionarios_Id_Questionario` INT NOT NULL,
  PRIMARY KEY (`idtb_Respostas`, `Tb_Questionarios_Id_Questionario`),
  INDEX `fk_Tb_Respostas_Tb_Questionarios1_idx` (`Tb_Questionarios_Id_Questionario` ASC) ,
  CONSTRAINT `fk_Tb_Respostas_Tb_Questionarios1`
    FOREIGN KEY (`Tb_Questionarios_Id_Questionario`)
    REFERENCES `SIAS`.`Tb_Questionarios` (`Id_Questionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
